# Generated by Django 6.0.3 on 2026-03-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_principal_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electronics & Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('BBA', 'Business Administration'), ('MBA', 'Master of Business Administration')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electronics & Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('BBA', 'Business Administration'), ('MBA', 'Master of Business Administration')], max_length=10, null=True),
        ),
    ]
