# Generated by Django 6.0.3 on 2026-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course_department_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Application'), ('ENG', 'Communication & Language'), ('EC', 'Electronics & Communication'), ('MATH', 'Mathematics'), ('COM', 'Commerce'), ('BA', 'Business Administration'), ('AI', 'AI & ML'), ('DS', 'Data Science')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Application'), ('ENG', 'Communication & Language'), ('EC', 'Electronics & Communication'), ('MATH', 'Mathematics'), ('COM', 'Commerce'), ('BA', 'Business Administration'), ('AI', 'AI & ML'), ('DS', 'Data Science')], max_length=10, null=True),
        ),
    ]
