# Generated by Django 6.0.3 on 2026-03-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_course_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
